package io.github.stardragonstudios.sol.backend.c;

import io.github.stardragonstudios.sol.semantics.FunctionSymbol;
import io.github.stardragonstudios.sol.semantics.ModuleName;
import io.github.stardragonstudios.sol.semantics.SemanticModel;
import io.github.stardragonstudios.sol.semantics.SemanticProgramAnalysisResult;
import io.github.stardragonstudios.sol.syntax.FunctionDeclaration;
import io.github.stardragonstudios.sol.syntax.ReturnStatement;
import io.github.stardragonstudios.sol.syntax.Statement;
import io.github.stardragonstudios.sol.syntax.TypeReference;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

final class CProgramGenerator {
    private final CSourceWriter writer = new CSourceWriter();
    private final List<FunctionContext> functions;
    private final CFunctionNameTable functionNames;

    CProgramGenerator(SemanticProgramAnalysisResult program) {
        Objects.requireNonNull(program, "Generated semantic program must not be null.");

        var seeds = collectFunctions(program);

        functionNames = new CFunctionNameTable(seeds.stream().map(FunctionSeed::function).toList());
        functions = seeds.stream().map(
                seed ->
                    new FunctionContext(
                        seed.moduleName(),
                        seed.model(),
                        seed.function(),
                        new CParameterNameTable(seed.model(), seed.function())
                    )
            ).toList();
    }

    CTranslationUnit generate() {
        emitHeader();
        writer.blankLine();

        emitPrimitiveAliases();
        writer.blankLine();

        emitFunctionDeclarations();
        writer.blankLine();

        emitFunctionDefinitions();

        return new CTranslationUnit(writer.source());
    }

    private void emitHeader() {
        writer.line("/*");
        writer.line(" * Generated by the Sol compiler.");
        writer.line(" * Do not edit manually.");
        writer.line(" */");
    }

    private void emitPrimitiveAliases() {
        writer.line("typedef long long sol_int;");
        writer.line("typedef double sol_float;");
        writer.line("typedef int sol_boolean;");
        writer.line("typedef unsigned int sol_char;");
    }

    private void emitFunctionDeclarations() {
        for (var context : functions) {
            var storage = context.function().declaration().body().isPresent() ? "static" : "extern";

            writer.line(signature(context, storage) + ";");
        }
    }

    private void emitFunctionDefinitions() {
        var emittedDefinition = false;

        for (var context : functions) {var body = context.function().declaration().body();

            if (body.isEmpty()) continue;
            if (emittedDefinition) writer.blankLine();

            writer.openBlock(signature(context, "static"));

            var expressionGenerator = new CExpressionGenerator(
                    context.model(),
                    context.moduleName(),
                    context.function(),
                    context.parameterNames()
            );

            for (var statement : body.orElseThrow().statements()) emitStatement(context, expressionGenerator, statement);

            writer.closeBlock();
            emittedDefinition = true;
        }
    }

    private String signature(FunctionContext context, String storage) {
        var declaration = context.function().declaration();
        var returnType = resolvedTypeOf(context, declaration.returnType(), "return type");
        var parameters = new ArrayList<String>(declaration.parameters().size());

        for (var parameter : declaration.parameters()) {
            var symbol = context.model().symbolOf(parameter)
                .orElseThrow(
                    () -> new IllegalStateException(
                        "Semantic model has no symbol for parameter '%s' of function '%s' in module '%s'."
                            .formatted(
                                parameter.name(),
                                context.function().name(),
                                context.moduleName().qualifiedName()
                            )
                    )
                );

            var type = resolvedTypeOf(context, parameter.type(), "parameter type");

            parameters.add("%s %s".formatted(type, context.parameterNames().nameOf(symbol)));
        }

        var parameterList = parameters.isEmpty() ? "void" : String.join(", ", parameters);

        return "%s %s %s(%s)".formatted(storage, returnType, functionNames.nameOf(context.function()), parameterList);
    }

    private String resolvedTypeOf(FunctionContext context, TypeReference reference, String description) {
        var type = context.model().typeOf(reference).orElseThrow(
            () -> new IllegalStateException(
                "Semantic model has no %s association for function '%s' in module '%s'."
                    .formatted(
                        description,
                        context.function().name(),
                        context.moduleName().qualifiedName()
                    )
            )
        );

        return CTypeGenerator.generate(type, context.moduleName(), context.function());
    }

    private void emitStatement(FunctionContext context, CExpressionGenerator expressionGenerator, Statement statement) {
        if (statement instanceof ReturnStatement returnStatement) {
            if (returnStatement.expression().isEmpty()) writer.line("return;");
            else writer.line("return %s;".formatted(expressionGenerator.generate(returnStatement.expression().orElseThrow())));

            return;
        }

        throw new CCodeGenerationException(
            CCodeGenerationException.Reason.UNSUPPORTED_STATEMENT,
            "Cannot generate %s in function '%s' of module '%s'.".formatted(
                    statement.getClass().getSimpleName(),
                    context.function().name(),
                    context.moduleName().qualifiedName()
            )
        );
    }

    private static List<FunctionSeed> collectFunctions(SemanticProgramAnalysisResult program) {
        var functions = new ArrayList<FunctionSeed>();

        for (var moduleName : program.moduleNames()) {
            var module = program.moduleOf(moduleName).orElseThrow(() -> new IllegalStateException(
                    "Semantic program has no module '%s'."
                        .formatted(moduleName.qualifiedName())
            ));

            var model = program.analysisOf(moduleName).orElseThrow(
                () -> new IllegalStateException(
                    "Semantic program has no analysis for module '%s'."
                        .formatted(moduleName.qualifiedName())
                )).model();

            for (var declaration : module.unit().declarations()) {
                if (!(declaration instanceof FunctionDeclaration functionDeclaration)) continue;

                var function =
                    model.symbolOf(functionDeclaration).orElseThrow(
                        () -> new IllegalStateException(
                            "Semantic model has no symbol for function '%s' in module '%s'."
                                .formatted(functionDeclaration.name(), moduleName.qualifiedName())
                        )
                    );

                functions.add(new FunctionSeed(moduleName, model, function));
            }
        }

        return List.copyOf(functions);
    }

    private record FunctionSeed(ModuleName moduleName, SemanticModel model, FunctionSymbol function) {}
    private record FunctionContext(ModuleName moduleName, SemanticModel model, FunctionSymbol function, CParameterNameTable parameterNames) { }
}
