package io.github.stardragonstudios.sol.backend.c;

import io.github.stardragonstudios.sol.lexer.Lexer;
import io.github.stardragonstudios.sol.parser.Parser;
import io.github.stardragonstudios.sol.semantics.ModuleName;
import io.github.stardragonstudios.sol.semantics.SemanticAnalyzer;
import io.github.stardragonstudios.sol.semantics.SourceModule;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class CCodeGeneratorTest {
    private static final String EXPECTED_SCAFFOLD =
        """
        /*
         * Generated by the Sol compiler.
         * Do not edit manually.
         */

        typedef int sol_generated_translation_unit;
        """;

    @Test
    void generatesTheCanonicalInitialScaffold() {
        var generated = CCodeGenerator.generate(validExecutableProgram());

        assertEquals(EXPECTED_SCAFFOLD, generated.source());
        assertFalse(generated.source().contains("\r"));
        assertFalse(generated.source().contains("\t"));
        assertTrue(generated.source().endsWith("\n"));
        assertFalse(generated.source().endsWith("\n\n"));
    }

    @Test
    void generationIsDeterministicAndStateIsIsolated() {
        var program = validExecutableProgram();
        var first = CCodeGenerator.generate(program);
        var second = CCodeGenerator.generate(program);

        assertEquals(first, second);
        assertNotSame(first, second);
    }

    @Test
    void doesNotModifyTheSemanticProgram() {
        var program = validExecutableProgram();
        var moduleNames = program.moduleNames();
        var entryPoint = program.entryPoint().orElseThrow();
        var moduleScope = program.analysisOf(moduleNames.getFirst())
                .orElseThrow()
                .model()
                .moduleScope();

        assertTrue(moduleScope.isFrozen());

        CCodeGenerator.generate(program);

        assertEquals(moduleNames, program.moduleNames());
        assertSame(entryPoint, program.entryPoint().orElseThrow());
        assertTrue(program.programDiagnostics().isEmpty());
        assertTrue(moduleScope.isFrozen());
    }

    @Test
    void rejectsNullSemanticProgram() {
        assertThrows(
            NullPointerException.class,
            () -> CCodeGenerator.generate(null)
        );
    }

    @Test
    void rejectsGeneralAnalysisWithoutResolvedEntryPoint() {
        var program = SemanticAnalyzer.analyzeModules(List.of(module(
            "library",
            """
                    fn helper() -> int
                        return 1
                    end
                    """
                )
            )
        );

        var exception =
            assertThrows(
                CCodeGenerationException.class,
                () -> CCodeGenerator.generate(program)
            );

        assertEquals(
            CCodeGenerationException.Reason.MISSING_ENTRY_POINT,
            exception.reason()
        );

        assertEquals(
            "Cannot generate C source: no executable entry point is resolved.",
            exception.getMessage()
        );
    }

    @Test
    void rejectsProgramLevelSemanticErrors() {
        var program =
            SemanticAnalyzer.analyzeProgram(
                List.of(
                    module(
                        "application",
                        """
                        fn helper() -> int
                            return 1
                        end
                        """
                    )
                )
            );

        var exception =
            assertThrows(
                CCodeGenerationException.class,
                () -> CCodeGenerator.generate(program)
            );

        assertEquals(
            CCodeGenerationException.Reason.PROGRAM_SEMANTIC_ERRORS,
            exception.reason()
        );

        assertEquals(
            "Cannot generate C source: program-level semantic errors are present.",
            exception.getMessage()
        );
    }

    @Test
    void rejectsModuleLevelSemanticErrors() {
        var program =
            SemanticAnalyzer.analyzeProgram(
                List.of(
                    module(
                        "application",
                        """
                        @init
                        fn launch() -> int
                            return missing()
                        end
                        """
                    )
                )
            );

        assertTrue(program.entryPoint().isPresent());

        var exception =
            assertThrows(
                CCodeGenerationException.class,
                () -> CCodeGenerator.generate(program)
            );

        assertEquals(
            CCodeGenerationException.Reason.MODULE_SEMANTIC_ERRORS,
            exception.reason()
        );

        assertEquals(
            "Cannot generate C source: module 'application' contains semantic errors.",
            exception.getMessage()
        );
    }

    @Test
    void failedGenerationDoesNotAffectLaterSuccessfulGeneration() {
        var invalid =
            SemanticAnalyzer.analyzeModules(
                List.of(
                    module(
                        "library",
                        """
                        fn helper() -> int
                            return 1
                        end
                        """
                    )
                )
            );

        assertThrows(
            CCodeGenerationException.class,
            () -> CCodeGenerator.generate(invalid)
        );

        assertEquals(
            EXPECTED_SCAFFOLD,
            CCodeGenerator.generate(validExecutableProgram()).source()
        );
    }

    @Test
    void generatedSourceContainsNoEnvironmentDependentValues() {
        var source = CCodeGenerator.generate(validExecutableProgram()).source();

        assertFalse(source.contains(System.getProperty("user.dir")));
        assertFalse(source.matches("(?s).*\\d{4}-\\d{2}-\\d{2}.*"));
        assertFalse(source.contains(System.lineSeparator().equals("\n") ? "\r" : System.lineSeparator()));
    }

    private static io.github.stardragonstudios.sol.semantics.SemanticProgramAnalysisResult
    validExecutableProgram() {
        return SemanticAnalyzer.analyzeProgram(
            List.of(
                module(
                    "application",
                    """
                    @init
                    fn launch() -> int
                        return 0
                    end
                    """
                )
            )
        );
    }

    private static SourceModule module(String name, String source) {
        return new SourceModule(
            new ModuleName(List.of(name.split("\\."))),
            Parser.parse(Lexer.scan(source))
        );
    }
}
