package io.github.stardragonstudios.sol.backend.c;

import io.github.stardragonstudios.sol.lexer.Lexer;
import io.github.stardragonstudios.sol.parser.Parser;
import io.github.stardragonstudios.sol.semantics.ModuleName;
import io.github.stardragonstudios.sol.semantics.SemanticAnalyzer;
import io.github.stardragonstudios.sol.semantics.SourceModule;

import org.junit.jupiter.api.Test;

import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class CFunctionGenerationTest {
    @Test
    void emitsDeclarationsBeforeDefinitionsInProgramOrder() {
        var source = generate(
            module(
                "library",
                """
                @fn external(value: int) -> int

                fn calculate(left: int, enabled: boolean) -> float
                    return 1.5
                end
                """
            ),
            module(
                "application",
                """
                fn finish() -> void
                    return
                end

                @init
                fn launch() -> int
                    return 0
                end
                """
            )
        );

        assertEquals(
            """
            /*
             * Generated by the Sol compiler.
             * Do not edit manually.
             */

            typedef long long sol_int;
            typedef double sol_float;
            typedef int sol_boolean;
            typedef unsigned int sol_char;

            extern sol_int sol_function_0(sol_int sol_parameter_0);
            static sol_float sol_function_1(sol_int sol_parameter_0, sol_boolean sol_parameter_1);
            static void sol_function_2(void);
            static sol_int sol_function_3(void);

            static sol_float sol_function_1(sol_int sol_parameter_0, sol_boolean sol_parameter_1) {
                return ((sol_float)1.5);
            }

            static void sol_function_2(void) {
                return;
            }

            static sol_int sol_function_3(void) {
                return ((sol_int)0);
            }
            """,
            source
        );
    }

    @Test
    void bodylessFunctionEmitsNoDefinition() {
        var source = generate(
            module(
                "application",
                """
                @fn external(value: int) -> int

                @init
                fn launch() -> int
                    return 0
                end
                """
            )
        );

        assertTrue(
            source.contains(
                "extern sol_int sol_function_0(sol_int sol_parameter_0);"
            )
        );

        assertEquals(
            1,
            occurrences(
                source,
                "sol_function_0("
            )
        );
    }

    @Test
    void zeroParameterFunctionUsesVoidParameterList() {
        var source = generate(
            module(
                "application",
                """
                @init
                fn launch() -> int
                    return 0
                end
                """
            )
        );

        assertTrue(
            source.contains(
                "static sol_int sol_function_0(void);"
            )
        );

        assertTrue(
            source.contains(
                "static sol_int sol_function_0(void) {"
            )
        );
    }

    @Test
    void parameterNumberingResetsForEveryFunction() {
        var source = generate(
            module(
                "application",
                """
                fn first(value: int) -> int
                    return value
                end

                @init
                fn second(other: int) -> int
                    return other
                end
                """
            )
        );

        assertTrue(
            source.contains(
                "static sol_int sol_function_0(sol_int sol_parameter_0);"
            )
        );

        assertTrue(
            source.contains(
                "static sol_int sol_function_1(sol_int sol_parameter_0);"
            )
        );

        assertEquals(
            0,
            occurrences(
                source,
                "sol_parameter_1"
            )
        );

        assertFalse(
            source.contains(
                "value"
            )
        );

        assertFalse(
            source.contains(
                "other"
            )
        );
    }

    @Test
    void sameSourceNameInSeparateModulesReceivesDistinctCNames() {
        var source = generate(
            module(
                "first",
                """
                fn helper() -> int
                    return 1
                end
                """
            ),
            module(
                "second",
                """
                fn helper() -> int
                    return 2
                end

                @init
                fn launch() -> int
                    return 0
                end
                """
            )
        );

        assertTrue(
            source.contains(
                "static sol_int sol_function_0(void);"
            )
        );

        assertTrue(
            source.contains(
                "static sol_int sol_function_1(void);"
            )
        );

        assertTrue(
            source.contains(
                "static sol_int sol_function_2(void);"
            )
        );

        assertFalse(
            source.contains(
                "helper"
            )
        );

        assertFalse(
            source.contains(
                "launch"
            )
        );
    }

    @Test
    void injectedFunctionsAreNotGeneratedTwice() {
        var source = generate(
            module(
                "library",
                """
                fn helper() -> int
                    return 1
                end
                """
            ),
            module(
                "application",
                """
                inject library

                @init
                fn launch() -> int
                    return 0
                end
                """
            )
        );

        assertEquals(
            2,
            occurrences(
                source,
                "sol_function_0("
            )
        );

        assertEquals(
            2,
            occurrences(
                source,
                "sol_function_1("
            )
        );

        assertFalse(
            source.contains(
                "sol_function_2"
            )
        );
    }

    @Test
    void entryPointIsGeneratedAsAnOrdinaryFunction() {
        var source = generate(
            module(
                "application",
                """
                @init
                fn start() -> int
                    return 0
                end
                """
            )
        );

        assertTrue(
            source.contains(
                "static sol_int sol_function_0(void)"
            )
        );

        assertFalse(
            source.contains(
                "int main("
            )
        );

        assertFalse(
            source.contains(
                " start("
            )
        );
    }

    private static String generate(
        SourceModule... modules
    ) {
        return CCodeGenerator.generate(
            SemanticAnalyzer.analyzeProgram(
                List.of(modules)
            )
        ).source();
    }

    private static SourceModule module(
        String name,
        String source
    ) {
        return new SourceModule(
            new ModuleName(
                List.of(
                    name.split("\\.")
                )
            ),
            Parser.parse(
                Lexer.scan(source)
            )
        );
    }

    private static int occurrences(
        String source,
        String searchedText
    ) {
        var count = 0;
        var offset = 0;

        while (true) {
            var match = source.indexOf(
                searchedText,
                offset
            );

            if (match < 0) {
                return count;
            }

            count++;
            offset = match
                + searchedText.length();
        }
    }
}
